# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='apt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
